### ISSUE TITLE
在运行爬虫的时候出错

### ISSUE THREAD

**Issue by zhanhao93** [lesywix/douban_group_spy#6]
其他步骤都正常，但是在run crawler_main的时候出现了错误，报错情况如下：

2021-04-08 01:29:39 INFO     start crawling group: 106955
2021-04-08 01:29:39 INFO     Getting group: 106955 successful
Traceback (most recent call last):
  File "D:\spider\douban_group_spy\venv\crawler_main.py", line 80, in crawl
    group = Group.objects.get(id=group_id)
  File "D:\spider\douban_group_spy\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\spider\douban_group_spy\venv\lib\site-packages\django\db\models\query.py", line 406, in get
    raise self.model.DoesNotExist(
douban_group_spy.models.DoesNotExist: Group matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\spider\douban_group_spy\venv\crawler_main.py", line 138, in <module>
    main()
  File "D:\spider\douban_group_spy\venv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "D:\spider\douban_group_spy\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "D:\spider\douban_group_spy\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\spider\douban_group_spy\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "D:\spider\douban_group_spy\venv\crawler_main.py", line 132, in main
    crawl(g_id, pages, keywords, exclude)
  File "D:\spider\douban_group_spy\venv\crawler_main.py", line 85, in crawl
    id=g_info['uid'],
KeyError: 'uid'

请问一下这是什么原因啊？

**Comment by lesywix** [comment]
豆瓣的 API 不让访问了
